apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulse-python-app
  labels:
    app: pulse-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pulse-python-app
  template:
    metadata:
      labels:
        app: pulse-python-app
    spec:
      containers:
      - name: pulse-container
        # REEMPLAZA ESTO con tu imagen de ECR o DockerHub
        image: 415062481836.dkr.ecr.us-east-1.amazonaws.com/pulse-repo:latest 
        ports:
        - containerPort: 8080 # EL PUERTO QUE USA TU app.py
        env:
        - name: TARGET_URL
          value: "https://www.google.com"
        - name: POLL_INTERVAL
          value: "5"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"